name: cofradia-${COFRADIA_ENV}-web

services:
  web:
    image: ${COFRADIA_WEB_IMAGE}:${COFRADIA_WEB_VERSION}
    container_name: cofradia-${COFRADIA_ENV}-web
    labels:
      cofradia.environment: ${COFRADIA_ENV}
      cofradia.service: web
      cofradia.critical: "true"
    networks:
      - cofradia
    restart: unless-stopped

networks:
  cofradia:
    name: ${COFRADIA_DOCKER_NETWORK}
    external: true
